module.exports = [
  {
    id: "a1",
    item_name: "Income",
    amount: 1500,
    date: "2024-07-01",
    from: "Employer",
    category: "Income",
  },
  {
    id: "b2",
    item_name: "Savings Deposit",
    amount: 500,
    date: "2024-07-02",
    from: "Bank",
    category: "Savings",
  },
  {
    id: "c3",
    item_name: "Cat Food",
    amount: -30,
    date: "2024-07-03",
    from: "Pet Store",
    category: "Pets",
  },
  {
    id: "d4",
    item_name: "Groceries",
    amount: -100,
    date: "2024-07-04",
    from: "Grocery Store",
    category: "Food",
  },
  {
    id: "e5",
    item_name: "Gym Membership",
    amount: -50,
    date: "2024-07-05",
    from: "Gym",
    category: "Fitness",
  },
  {
    id: "f6",
    item_name: "Electricity Bill",
    amount: -75,
    date: "2024-07-06",
    from: "Utility Company",
    category: "Utilities",
  },
  {
    id: "g7",
    item_name: "Dining Out",
    amount: -40,
    date: "2024-07-07",
    from: "Restaurant",
    category: "Entertainment",
  },
  {
    id: "h8",
    item_name: "Internet Bill",
    amount: -60,
    date: "2024-07-08",
    from: "ISP",
    category: "Utilities",
  },
  {
    id: "i9",
    item_name: "Book Purchase",
    amount: -20,
    date: "2024-07-09",
    from: "Bookstore",
    category: "Education",
  },
  {
    id: "j0",
    item_name: "Bus Pass",
    amount: -25,
    date: "2024-07-10",
    from: "Transport Company",
    category: "Transport",
  },
];
